CSK/urls.py
from django.urls import path

from CSK.views import *

app_name='CSK'

urlpatterns=[
    path('Dhoni/',Dhoni,name='Dhoni'),
    
]

RCB/urls.py
from django.urls import path

from RCB.views import *


app_name='RCB'

urlpatterns=[
    path('Kohli/',Kohli,name='Kohli'),
]

project5/urls.py
from django.contrib import admin
from django.urls import path,include
# from app.views import *
import CSK,RCB
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('First/',wish,name='wish'),
    path('RCB/',include('RCB.urls')),
    path('CSK/',include('CSK.urls')),

]

CSK/models.py
from django.db import models

# Create your models here.

RCB/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models

# Create your models here.

CSK/views.py
from django.shortcuts import render

# Create your views here.
def Dhoni(request):
    return render(request,'csk.html')

RCB/views.py
from django.shortcuts import render

# Create your views here.
def Kohli(request):
    return render(request,'rcb.html')

app/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def wish(request):
    date=datetime.datetime.now()
    msg="hello friends very very"
    h=int(date.strftime('%H'))
    if h<12:
        msg+='Goodmorning'
    elif h<16:
        msg+='Good afternoon'
    elif h<21:
        msg+="good evening"
    else:
        msg+='good night'
    d={'insert_date':date,'insert_msg':msg}
    return render(request,'first.html',d)

templates/csk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSK PAGE</title>
    <style>
        h1{
            color: brown;
        }
        h2{
            color: chocolate;
        }
    </style>
</head>
<body>
    <center>
        <h1>Chennai Super Kings</h1>
        <h2>Captain Cool MSD</h2>
<br>
        <a href="{% url 'RCB:Kohli' %}">navigate to kohli page</a>
    </center>
</body>
</html>

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template page</title>
    <style>
        h1{
            color: blue;
        }
        h2{
            color: aqua;

        }
        h3{
            color: blueviolet;
        }
    </style>
</head>
<body>
    <center>
        <h1>Template Pages</h1>
        <h2>{{insert_msg}}</h2>
        <h3>the current date & time is:{{ insert_date }}</h3>
    </center>
</body>
</html>

templates/rcb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RCB PAGE</title>
    <style>
        h1{
            color: brown;
        }
        h2{
            color: chocolate;
        }
    </style>
</head>
<body>
    <center>
        <h1>Royal challages Bangalore</h1>
        <h2>Run Machine Virat Kohli</h2>
        <br>
        <a href="{% url 'CSK:Dhoni' %}">navigate to Dhoni page</a>
    </center>
</body>
</html>